const express = require('express');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const cors = require('cors');
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;

// Security middleware
app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'public')));

// Rate limiting
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100, // limit each IP to 100 requests per windowMs
  message: 'Too many requests from this IP, please try again later.'
});
app.use('/api/', limiter);

// Load names data with error handling
let firstNames = ["Lucky", "Shamrock", "Emerald", "Goldie", "Clover"];
let lastNames = ["O'Green", "McShamrock", "Fitzpatrick", "O'Malley", "Gallagher"];
let descriptors = ["the Lucky", "of the Rainbow", "Gold-Hunter", "Clover-Finder", "Emerald-Eyed"];

try {
  const namesData = JSON.parse(fs.readFileSync(path.join(__dirname, 'names.json'), 'utf8'));
  if (namesData.first_names && Array.isArray(namesData.first_names)) {
    firstNames = namesData.first_names;
  }
  if (namesData.last_names && Array.isArray(namesData.last_names)) {
    lastNames = namesData.last_names;
  }
  if (namesData.descriptors && Array.isArray(namesData.descriptors)) {
    descriptors = namesData.descriptors;
  }
  console.log('Names data loaded successfully');
} catch (error) {
  console.error('Error loading names.json, using default names:', error.message);
}

// Helper function to generate a random leprechaun name
function generateLeprechaunName() {
  const firstName = firstNames[Math.floor(Math.random() * firstNames.length)];
  const lastName = lastNames[Math.floor(Math.random() * lastNames.length)];
  const descriptor = descriptors[Math.floor(Math.random() * descriptors.length)];
  return `${firstName} \"${descriptor}\" ${lastName}`;
}

// Helper function to generate PDF
function generatePDF(name, res) {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const filename = `leprechaun-name-${Date.now()}.pdf`;
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.setHeader('Content-Type', 'application/pdf');
  doc.pipe(res);
  
  // Add content
  doc.fontSize(25).text('Your Leprechaun Name', { align: 'center' });
  doc.moveDown();
  doc.fontSize(18).text(`Name: ${name}`, { align: 'center' });
  doc.moveDown();
  doc.fontSize(12).text('Generated by Leprechaun Name Generator', { align: 'center' });
  doc.fontSize(10).text('© YemaDesignStudio - All rights reserved', { align: 'center' });
  
  doc.end();
}

// API endpoint to generate a name
app.get('/api/generate', (req, res) => {
app.get('/api/health', (req, res) => {
  res.json({ status: 'healthy', timestamp: new Date().toISOString() });
});
  try {
    const name = generateLeprechaunName();
    res.json({ name });
  } catch (error) {
    console.error('Error generating name:', error);
    res.status(500).json({ error: 'Failed to generate name' });
  }
});

// API endpoint to download PDF
app.get('/api/download-pdf', (req, res) => {
  try {
    const name = req.query.name || generateLeprechaunName();
    generatePDF(name, res);
  } catch (error) {
    console.error('Error generating PDF:', error);
    res.status(500).json({ error: 'Failed to generate PDF' });
  }
});

// Debug endpoint
app.get('/api/debug', (req, res) => {
  try {
    const fs = require("fs");
    const path = require("path");
    const filePath = path.join(__dirname, "names.json");
    res.json({
      dirname: __dirname,
      filePath: filePath,
      fileExists: fs.existsSync(filePath),
      error: null
    });
  } catch (error) {
    res.json({
      dirname: __dirname,
      filePath: null,
      fileExists: false,
      error: error.message
    });
  }
});

// Health check endpoint
app.get('/health', (req, res) => {
  res.status(200).json({ status: 'ok', timestamp: new Date().toISOString() });
});

// Start server
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
